version: "3"

services:
    rabbitmq:
        container_name: amqp-exam
        image: rabbitmq:3-management
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
            RABBITMQ_DEFAULT_VHOST: /
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - ./rabbitmq:/var/lib/rabbitmq
    postgresql:
        container_name: postgresql-exam
        image: postgres:11.6
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: pass123
        volumes:
            - ./postgresql:/var/lib/postgresql/data
